services:
  mysql:
    image: 'mysql:8.0.39'
    container_name: 'mysql_alurafood'
    restart: 'always'
    environment:
      - 'MYSQL_DATABASE=alurafood_pagamento'
      - 'MYSQL_USER=alurafood'
      - 'MYSQL_PASSWORD=alurafood123'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
  postgres:
    image: 'postgres:14'
    container_name: 'postgresql_alurafood'
    restart: 'always'
    environment:
      - 'POSTGRES_DB=alurafood_pedido'
      - 'POSTGRES_USER=alurafood'
      - 'POSTGRES_PASSWORD=alurafood123'
      - 'PGDATA=/var/lib/postgresql/data'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3.13.7-management'
    container_name: 'rabbitmq'
    hostname: 'rabbitmq' # Sets the container's hostname
    restart: 'always'
    configs:
      - source: plugins
        target: /etc/rabbitmq/enabled_plugin
    environment:
       - 'RABBITMQ_ENABLED_PLUGINS: rabbitmq_shovel, rabbitmq_shovel_management' # Example: enabling MQTT and Shovel plugins, or rabbitmq_mqtt
#      - 'RABBITMQ_DEFAULT_USER=admin' # Sets the default RabbitMQ username
#      - 'RABBITMQ_DEFAULT_PASS=adminadmin' # Sets the default RabbitMQ password (change for production)
    ports:
      - '5672:5672' # Maps the AMQP port (for client connections)
      - '15672:15672' # Maps the management UI port (for web interface access)
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq' # Persists RabbitMQ data to a local directory
#      - './enabled_plugins:/etc/rabbitmq/enabled_plugins'
#      - "./data:/var/lib/rabbitmq" # Persists RabbitMQ data to a local directory
#    healthcheck: # Defines a health check to ensure RabbitMQ is running
#      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
#      interval: 30s
#      timeout: 30s
#      retries: 3

#    healthcheck:
#      test:
#        - CMD
#        - rabbitmq-diagnostics
#        - '-q'
#        - ping
#      retries: 3
#      timeout: 5s

configs:
  plugins:
    content: '[rabbitmq_shovel, rabbitmq_shovel_management]'
volumes:
  mysql_data:
  postgres_data:
  rabbitmq_data:

#  mysql-pagamento:
#    image: 'mysql:8.0.39'
#    environment:
#      - 'MYSQL_DATABASE=alurafood-pagamento'
#      - 'MYSQL_PASSWORD=alurafood123'
#      - 'MYSQL_ROOT_PASSWORD=root'
#      - 'MYSQL_USER=alurafood'
#    ports:
#      - '3306:3306'
#    volumes:
#      - 'mysql_data:/var/lib/mysql'

#  mysql-pedido:
#    image: 'mysql:8.0.39'
#    environment:
#      - 'MYSQL_DATABASE=alurafood-pedido'
#      - 'MYSQL_PASSWORD=alurafood123'
#      - 'MYSQL_ROOT_PASSWORD=root'
#      - 'MYSQL_USER=alurafood'
#    ports:
#      - '3307:3306'
#    volumes:
#      - 'mysql_data:/var/lib/mysql'

