services:
  mysql:
    image: 'mysql:8.0.39'
    environment:
      - 'MYSQL_DATABASE=alurafood-pagamento'
      - 'MYSQL_PASSWORD=alurafood123'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=alurafood'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
volumes:
  mysql_data: